### ISSUE TITLE
Greyscale version background is not to same scale as colour

### ISSUE THREAD

**Issue by davetaz** [theodi/data-ethics-canvas#1]
So text ends up in incorrect location. This needs investigating.

**Comment by jschof1** [comment]
![image](https://user-images.githubusercontent.com/59843981/121011100-22ea5c80-c78e-11eb-9f47-b6d56bc2391d.png)
difference shown here

**Comment by jschof1** [comment]
![Re-scaled-grey](https://user-images.githubusercontent.com/59843981/121015997-8aef7180-c793-11eb-980a-1396a0ae000e.jpg)
Here is the new working image
